### ISSUE TITLE
Support negative temperatures

### ISSUE THREAD

**Issue by avbentem** [SensationalSystems/tektelic-kona-decoder#1]
Unless temperature readings are in Kelvin, you'll want to support negative values. This won't do:

```javascript
params.temperature = 0.1 * ((bytes[i+2] << 8) | bytes[i+3]);
```

You might need the following, but not knowing how things are encoded, and not owning any of the devices, it's just a wild guess:

```javascript
// Sign-extend to 32 bits to support negative values, by shifting 24 bits
// (16 too far) to the left, followed by a sign-propagating right shift:
params.temperature = (bytes[i+2]<<24>>16 | bytes[i+3]) / 10;
```

Here, I also replaced multiplication by 0.1 (which [cannot be represented in an exact JavaScript IEEE 754 floating point](https://floating-point-gui.de/)) with division by 10, increasing the chances for an exact result:

```text
131 / 10 = 13.1
0.1 * 131 = 13.100000000000001
```

Or, to explictly limit the number of decimals:

```javascript
// Sign-extend to 32 bits to support negative values, by shifting 24 bits
// (16 too far) to the left, followed by a sign-propagating right shift, and
// unary plus to cast the string result of toFixed to a proper number:
params.temperature = +(0.1 * (bytes[i+2]<<24>>16 | bytes[i+3])).toFixed(1);
```

(As an aside: I also find it odd to see `i = i+2` for the PIR activity reading, while at that point `bytes[i+2]` has not been processed.)

**Comment by eggfriedrice** [comment]
Many thanks for your suggestion here, I read the docs for the sensor again and tested your code, it worked fine.

I've incorporated your fixes and added a note about your contribution to the Readme.

Thanks again!
